### ISSUE TITLE
Nuevo README

### ISSUE THREAD

**Issue by aguzmant103** [Ethereum-Costa-Rica/ethereum.cr#16]
Generar un nuevo readme para el repositorio de ethereum.cr website

**Comment by Gerson2102** [comment]
En esto podría ayudar. Porque las tecnologías que están usando las conozco muy poco.

**Comment by aguzmant103** [comment]
Genial go for it! 

No tenemos nada estructurado pero sugeriria seguir guias tipo: https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/

Y agregar areas como:
- Como me puedo unir a la comunidad (Telegram, LinkedIn, Meetup, Instagram, Twitter, etc)
- Como puedo contribuir (Issues, ideas, etc)
- Etc
