### ISSUE TITLE
New organization intro 

### ISSUE THREAD

**Issue by aguzmant103** [Ethereum-Costa-Rica/ethereum.cr#19]
Add a description in English and Spanish about Ethereum Costa Rica in GitHub org profile

**Comment by Ayoazeez26** [comment]
@aguzmant103 can I work on this?

**Comment by aguzmant103** [comment]
Go for it! Give it a shot :)

Try to mention a few key concepts:
- This is a community-driven organization
- Values of openness, transparency, open-source 
- Focused on education and adoption
- Building public-goods
- Creating events and meetups and courses and workshops

Also feel free to get inspiration from other big web3 open-source communities
