### ISSUE TITLE
Internationalize Website

### ISSUE THREAD

**Issue by aguzmant103** [Ethereum-Costa-Rica/ethereum.cr#20]
Make sure Ethereum.cr automatically translates between English/Spanish.

**Comment by Ayoazeez26** [comment]
@aguzmant103 I checked Ethereum.cr and the translate works as expected, is there any specific thing you need work on?

**Comment by JustinCast** [comment]
Closing as this would be included in the website v2.
https://github.com/Ethereum-Costa-Rica/ethereum.cr/pull/41/files#diff-4840952983d2a94f27deb00bf7247347345b60e3a96dc2aa41a6a50ecacdf1b6
