### ISSUE TITLE
Research about similar events websites

### ISSUE THREAD

**Issue by JustinCast** [Ethereum-Costa-Rica/ethereum.cr#30]
#### Main Features
- Event map
- Ethos (a brief but meaningful description of the event)
- Blog
- Gaming Area
- Glossary

**Comment by JustinCast** [comment]
## [Devcon](https://devcon.org/en/)
### Main Features
- Blog posts
- Past Events (Puede ser un Eth Cr Day recap), ver https://blog.ethereum.org/en/2022/11/17/devcon-vi-wrap
    - Photos
    - Videos
#### Notes
Payment option in devcon is https://3cities.xyz/

**Comment by robertram** [comment]
@JustinCast 
Can you see this website please? 
[EthCincoDeMayo](https://ethcincodemayo.com/)

We need the following sections to be in our landing page:

- Hackathon
- Speakers
    - Sección para speakers
    - Página individual para cada speaker
- Sección para los eventos relacionados a Ethereum Costa Rica
    - Workshops, charlas, ideatons, hackathons
- Sección para eventos pasados
- Sección de core contributors
- Sección para partners y sponsors
- FAQ
- Testimonials
- Venue
- Gallery
- Contact Form
- Social Media section
- Blog (we can have the EthCR Day recap in the blog)

Note: I can implement contentful so we can manage all of our content and internationalization there.
