### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by JustinCast** [Ethereum-Costa-Rica/ethereum.cr#35]
Implement a mailing list on the website.
@Coderoostr also you can research about similar mailing list

**Comment by robertram** [comment]
The mailist list was implemented by @Coderoostr 
An email is sent to ethereumcostarica@gmail.com every time a user enters their email in the newsletter form. 


![Image](https://github.com/Ethereum-Costa-Rica/ethereum.cr/assets/37461123/0f057fea-a07e-4a7f-911e-549664dd3517)


A new task related to this would be adding the users to the contacts list so we can export that contact list as a csv once we need it

![Image](https://github.com/Ethereum-Costa-Rica/ethereum.cr/assets/37461123/3db4fa73-5086-41df-914c-73ec572a0fe3)

**Comment by Coderoostr** [comment]
Done
