### ISSUE TITLE
Update donation address to new adress

### ISSUE THREAD

**Issue by aguzmant103** [Ethereum-Costa-Rica/ethereum.cr#40]
Old address: 0x5EAD82e959D8218f6003526AB8d457972B679C41
New multisig address: 0x0004d7D8843Ba256f0CA0d835C0977C5D5375285

Note: for sensitive-related changes always ask for double and triple confirmation!! (we don't want future scammers changing ethereum.cr address)

**Comment by Coderoostr** [comment]
Ready
Please check, thanks!

**Comment by aguzmant103** [comment]
Lgtm!
