### ISSUE TITLE
Add users emails to EmailJS contacts list

### ISSUE THREAD

**Issue by robertram** [Ethereum-Costa-Rica/ethereum.cr#43]
Add the users to the contacts list so we can export that contact list as a csv once we need it

![Image](https://github.com/Ethereum-Costa-Rica/ethereum.cr/assets/37461123/d4ef5b01-2715-478a-9967-4298224c63c2)

**Comment by Coderoostr** [comment]
![image](https://github.com/Ethereum-Costa-Rica/ethereum.cr/assets/103231131/57d78098-fde2-4dbf-a060-8e42a63b9ae4)
